# Generated by Django 5.2 on 2025-04-25 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(limit_choices_to={'user': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, on_delete=django.db.models.deletion.CASCADE, to='financials.category'),
        ),
    ]
