# Generated by Django 4.2.20 on 2025-04-26 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0006_alter_transaction_options_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
