# Generated by Django 4.2.20 on 2025-04-26 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financials", "0007_delete_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category_list",
                    models.ManyToManyField(blank=True, to="financials.category"),
                ),
                (
                    "transaction_list",
                    models.ManyToManyField(blank=True, to="financials.transaction"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
