# Generated by Django 4.2.20 on 2025-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0008_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="expense",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="account",
            name="income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
