# Generated by Django 4.2.20 on 2025-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0010_account_budget_alter_transaction_id_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
