# Generated by Django 4.2.20 on 2025-04-27 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0011_alter_category_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
