# Generated by Django 4.2.20 on 2025-04-27 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0014_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="budget",
        ),
    ]
