# Generated by Django 4.2.20 on 2025-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0015_remove_account_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
